### ISSUE TITLE
Broken build with SCons 3.1.1

### ISSUE THREAD

**Issue by ptomulik** [ztmir/ztmir-texfactory#72]
We've got the following error:

```
scons: *** [build/latex/papers/qnxlab/qnxlab-0.1.pdf] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xf3 in position 41860: invalid continuation byte
Traceback (most recent call last):
  File "/home/ptomulik/projects/ztmir-texfactory/.venv/lib/python3.7/site-packages/scons/SCons/Action.py", line 1209, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/home/ptomulik/projects/ztmir-texfactory/.venv/lib/python3.7/site-packages/scons/SCons/Tool/pdftex.py", line 60, in PDFTeXLaTeXFunction
    result = PDFLaTeXAuxAction(target,source,env)
  File "/home/ptomulik/projects/ztmir-texfactory/.venv/lib/python3.7/site-packages/scons/SCons/Tool/pdftex.py", line 49, in PDFLaTeXAuxAction
    result = SCons.Tool.tex.InternalLaTeXAuxAction( PDFLaTeXAction, target, source, env )
  File "/home/ptomulik/projects/ztmir-texfactory/.venv/lib/python3.7/site-packages/scons/SCons/Tool/tex.py", line 301, in InternalLaTeXAuxAction
    logContent = f.read()
  File "/home/ptomulik/projects/ztmir-texfactory/.venv/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 41860: invalid continuation byte
```

The reason is, that ``*.log`` files generated by TexLive are not utf-8. It seems that next SCons version fixes this but it's not released yet. We can wait a while and then raise the required version in ``requirements.txt``.

**Comment by ptomulik** [comment]
SCons 3.1.2 is out. I'll bump the version in requirements.txt, so closing this issue.
